### your site title here
remote_theme: "jitinnair1/gradfolio"
title: Julia Stabinska, PhD
description:


baseurl: "" #name of GitHub repository
url: "" #custom url to be used instead of GitHub repository
email: stabin3@jhmi.edu

highlighter: rouge
markdown: kramdown

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
#facebook: "#"
twitter: "#"
linkedin: "#"
github: "#"
researchgate: "#"
orcid: "#"

keywords: MRI, renal MRI, kidney MRI, renal CEST, renal DWI, iopamidol, pH imaging

highlighter: rouge
markdown: kramdown

# Tracker
analytics:

#optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /publications/:path/

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
